spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api
logging:
  level:
    root: debug
decorator:
  datasource:
    p6spy:
      enable-logging: true
